export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_ERROR = 'UPDATE_PRODUCT_ERROR';
export const UPDATE_PRODUCT_PURGE = 'UPDATE_PRODUCT_PURGE';

export const LOAD_PRODUCT_SUCCESS = 'LOAD_PRODUCT_SUCCESS';
export const LOAD_PRODUCT_ERROR = 'LOAD_PRODUCT_ERROR';
export const LOAD_PRODUCT_PURGE = 'LOAD_PRODUCT_PURGE';

export const SAVE_PRODUCT_SUCCESS = 'SAVE_PRODUCT_SUCCESS';
export const SAVE_PRODUCT_ERROR = 'SAVE_PRODUCT_ERROR';
export const SAVE_PRODUCT_PURGE = 'SAVE_PRODUCT_PURGE';


export const LOAD_PRODUCT_HISTORY_SUCCESS = 'LOAD_PRODUCT_HISTORY_SUCCESS';
export const LOAD_PRODUCT_HISTORY_ERROR = 'LOAD_PRODUCT_HISTORY_ERROR';
export const LOAD_PRODUCT_HISTORY_PURGE = 'LOAD_PRODUCT_HISTORY_PURGE';

export const SEARCH_PRODUCT_SUCCESS = 'SEARCH_PRODUCT_SUCCESS';
export const SEARCH_PRODUCT_ERROR = 'SEARCH_PRODUCT_ERROR';
export const SEARCH_PRODUCT_PURGE = 'SEARCH_PRODUCT_PURGE';