import { createStore, applyMiddleware } from 'redux';
import reducer from './reducers';
import thunk from 'redux-thunk';
import {composeWithDevTools} from 'redux-devtools-extension';
import {createLogger} from 'redux-logger';

const logger = createLogger({
    /* https://github.com/evgenyrodionov/redux-logger */
    collapsed: true,
    diff: true
});


const initialState = {
    calculator: {
        "cantidad": "",
        "type": "quantity",
        "disabledPrice": true,
    },
    cardEditItem : {
		   "id": 2,	
		   "precioCompra":14.0,
		   "codigointerno":"14",
		   "proveedor":"trupper",
		   "description":"Codo 13 x 90 cobre",
		   "codigoProveedor":"49506",
		   "precioVenta":10.0,
		   "ubicacion":"",
		   "barcode":"7506240621234",
		   "existencia":7,
		   "cantidad": 2,
		   "total": 20.0,
		   "active": false,
	},
	listaConsulta: [
		{
		   "id": 1,	
		   "precioCompra":12.0,
		   "codigointerno":"358",
		   "proveedor":"trupper",
		   "description":"Palanca de plastico para wc",
		   "codigoProveedor":"49504",
		   "precioVenta":18.0,
		   "ubicacion":"",
		   "barcode":"7506240620037",
		   "existencia":7,
		   "cantidad": 1,
		   "total": 10.0,
		},
		{
		   "id": 2,	
		   "precioCompra":14.0,
		   "codigointerno":"14",
		   "proveedor":"trupper",
		   "description":"Codo 13 x 90 cobre",
		   "codigoProveedor":"49506",
		   "precioVenta":10.0,
		   "ubicacion":"",
		   "barcode":"7506240621234",
		   "existencia":7,
		   "cantidad": 2,
		   "total": 20.0,
		   "active": false,
		},
		{
		   "id": 3,	
		   "precioCompra":14.0,
		   "codigointerno":"15",
		   "proveedor":"trupper",
		   "description":"Codo 13 x 90 cobre",
		   "codigoProveedor":"49506",
		   "precioVenta":10.0,
		   "ubicacion":"",
		   "barcode":"7506240621234",
		   "existencia":7,
		   "cantidad": 2,
		   "total": 20.0,
		   "active": true,
		},
		{
		   "id": 4,	
		   "precioCompra":14.0,
		   "codigointerno":"15",
		   "proveedor":"trupper",
		   "description":"Codo 13 x 90 cobre",
		   "codigoProveedor":"49506",
		   "precioVenta":10.0,
		   "ubicacion":"",
		   "barcode":"7506240621234",
		   "existencia":7,
		   "cantidad": 2,
		   "total": 20.0,
		   "active": true,
		},
		{
		   "id": 5,	
		   "precioCompra":14.0,
		   "codigointerno":"15",
		   "proveedor":"trupper",
		   "description":"Codo 13 x 90 cobre",
		   "codigoProveedor":"49506",
		   "precioVenta":10.0,
		   "ubicacion":"",
		   "barcode":"7506240621234",
		   "existencia":7,
		   "cantidad": 2,
		   "total": 20.0,
		   "active": true,
		},
		{
		   "id": 6,	
		   "precioCompra":14.0,
		   "codigointerno":"15",
		   "proveedor":"trupper",
		   "description":"Codo 13 x 90 cobre",
		   "codigoProveedor":"49506",
		   "precioVenta":10.0,
		   "ubicacion":"",
		   "barcode":"7506240621234",
		   "existencia":7,
		   "cantidad": 2,
		   "total": 20.0,
		   "active": true,
		},
		{
		   "id": 7,	
		   "precioCompra":14.0,
		   "codigointerno":"15",
		   "proveedor":"trupper",
		   "description":"Codo 13 x 90 cobre",
		   "codigoProveedor":"49506",
		   "precioVenta":10.0,
		   "ubicacion":"",
		   "barcode":"7506240621234",
		   "existencia":7,
		   "cantidad": 2,
		   "total": 20.0,
		   "active": true,
		},
		{
		   "id": 8,	
		   "precioCompra":14.0,
		   "codigointerno":"15",
		   "proveedor":"trupper",
		   "description":"Codo 13 x 90 cobre",
		   "codigoProveedor":"49506",
		   "precioVenta":10.0,
		   "ubicacion":"",
		   "barcode":"7506240621234",
		   "existencia":7,
		   "cantidad": 2,
		   "total": 20.0,
		   "active": true,
		},
		{
		   "id": 9,	
		   "precioCompra":14.0,
		   "codigointerno":"15",
		   "proveedor":"trupper",
		   "description":"Codo 13 x 90 cobre",
		   "codigoProveedor":"49506",
		   "precioVenta":10.0,
		   "ubicacion":"",
		   "barcode":"7506240621234",
		   "existencia":7,
		   "cantidad": 2,
		   "total": 20.0,
		   "active": true,
		},
		{
		   "id": 10,	
		   "precioCompra":14.0,
		   "codigointerno":"15",
		   "proveedor":"trupper",
		   "description":"Codo 13 x 90 cobre",
		   "codigoProveedor":"49506",
		   "precioVenta":10.0,
		   "ubicacion":"",
		   "barcode":"7506240621234",
		   "existencia":7,
		   "cantidad": 2,
		   "total": 20.0,
		   "active": true,
		},

	],
}

const store = createStore(reducer, initialState,composeWithDevTools(
            /* logger must be the last middleware in chain to log actions */
            applyMiddleware(thunk, logger)  
        ));

export default store;